version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "5000"
      DB_HOST: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "mysecurepassword"
      POSTGRES_DB: "finance_app"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "mysecurepassword"
      POSTGRES_DB: "finance_app"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
